apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cino-bar.fullname" . }}-backend-config
  labels:
    {{- include "cino-bar.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  DB_HOST: {{ default (printf "%s.%s.svc.cluster.local" .Values.database.serviceName .Values.database.serviceNamespace) .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  SERVER_PORT: {{ .Values.backend.service.port | quote }}
  CORS_ALLOWED_ORIGINS: {{ include "cino-bar.corsAllowedOrigins" . | quote }}
