apiVersion: v1
kind: Service
metadata:
  name: {{ include "cino-bar.fullname" . }}-backend
  labels:
    {{- include "cino-bar.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/component: backend
    {{- include "cino-bar.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
