apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cino-bar.fullname" . }}-frontend
  labels:
    {{- include "cino-bar.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ default 1 .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      {{- include "cino-bar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        {{- include "cino-bar.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "cino-bar.fullname" . }}-frontend-config
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
