apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-credentials
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cino
    kind: ClusterSecretStore
  target:
    name: repo-github-cino
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
    - secretKey: url
      remoteRef:
        key: argocd/git
        property: url
    - secretKey: sshPrivateKey
      remoteRef:
        key: argocd/git
        property: sshPrivateKey
    - secretKey: sshKnownHosts
      remoteRef:
        key: argocd/git
        property: sshKnownHosts
