apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-credentials-staging
  namespace: infrastructure
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cino
    kind: ClusterSecretStore
  target:
    name: mysql-credentials-staging
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: cino/staging/backend
        property: DB_PASSWORD
